# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-03 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_learn_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='课程学习时长'),
        ),
    ]
