# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-03 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='needknow',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='tip',
            field=models.CharField(default='', max_length=300, verbose_name='老师提示'),
        ),
    ]
